# https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#release
#
# Creates an Expo Update with Expo branch named as the Git branch for clarity
#
#
name: ğŸš€ Build Android / iOS
run-name: ğŸš€ ${{ inputs.build-type }} build for ${{ inputs.platform }}
on:
  workflow_dispatch:
    inputs:
      # The build profiles are named the same as the channel they are linked to for convenience and simplicity.
      build-type:
        description: What type should be build?
        type: environment
        required: true

      platform:
        type: choice
        required: true
        description: For what OS?
        options: 
          - All
          - Android
          - iOS

jobs:
  build:
    name: ğŸ— EAS Build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Select EAS Build Profile from GitHub Environment
        run: |
          echo "EAS_BUILD_PROFILE=${inputs.build-type,,}" >>${GITHUB_ENV}

      - name: ğŸ“± Set platform
        run: |
          echo "EAS_BUILD_PLATFORM=${inputs.platform,,}" >>${GITHUB_ENV}

      # - name: ğŸ’© Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: ğŸ— Enable corepack
        run: |
          corepack enable
          yarn -v

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: ğŸš€ Create update
        # https://docs.github.com/en/github-ae@latest/webhooks-and-events/webhooks/webhook-events-and-payloads#release
        run: eas build --non-interactive --profile $EAS_BUILD_PROFILE --platform $EAS_BUILD_PLATFORM
