# https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#release
#
# Creates an Expo Update with Expo branch named as the Git branch for clarity
#
#
name: ğŸš€ Build Android & iOS
on:
  workflow_dispatch:
    inputs:
      build-type:
        description: Vilken version av appen ska byggas?
        type: environment
        required: true

jobs:
  build:
    name: ğŸ— EAS Build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Set type to Production build
        if: github.event.inputs.build-type == 'Production'
        run: |
          echo "BUILD_TYPE=production" >> $GITHUB_ENV

      - name: ğŸ— Set type to Development build
        if: github.event.inputs.build-type == 'Development'
        run: |
          echo "BUILD_TYPE=production" >> $GITHUB_ENV

      - name: ğŸ’© Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: ğŸ— Enable corepack
        run: |
          corepack enable
          yarn -v

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: ğŸš€ Create update
        # https://docs.github.com/en/github-ae@latest/webhooks-and-events/webhooks/webhook-events-and-payloads#release
        run: eas build --non-interactive --profile {{ github.event.inputs.build-type }} --platform all
