# https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#release
#
# Creates an Expo Update with Expo branch named as the Git branch for clarity
#
name: ğŸ¤– ğŸ“¦ Send release
run-name: ğŸ¤– ğŸ“¦ Send release '${{ github.event.release.name }}' to EAS Branch '${{ github.ref_name }}'
on:
  release:
    types: [published]

jobs:
  release:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      # This will automatically check-out to the ref/commit/release that triggered the event
      # In this case been the release & tag for it.
      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: ğŸ— Enable corepack
        run: |
          corepack enable
          yarn -v

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: ğŸ“¦ Send release to EAS
        # https://docs.github.com/en/github-ae@latest/webhooks-and-events/webhooks/webhook-events-and-payloads#release
        run: eas update --non-interactive --branch ${{ github.ref_name }} --message "${{ github.event.release.name }}"

      - name: ğŸ§¹ Clean autocreated EAS Channel
        # No idea why EAS is autocreating a EAS Channel with the EAS Branch name, just remove the EAS Channel as another one like 
        #   staging / production will eventually/possibly be linked to the branch later.
        run: eas channel:delete ${{ github.ref_name }} --non-interactive
