# https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#release
#
# Creates an Expo Update with Expo branch named as the Git branch for clarity
#
#
name: ğŸš€ Point release branch.
run-name: ğŸš€ Point Release branch '${{ inputs.eas-branch }}' to EAS Channel '${{ inputs.eas-channel }}'
on:
  workflow_dispatch:
    inputs:
      # This will publish an EAS Update to a EAS Branch named after the release name & Relink the EAS Channel selected to to this EAS Branch.
      # The build profiles are named the same as the channel they are linked to for convenience and simplicity.
      eas-channel:
        description: What Channel should receive the update?
        type: environment
        required: true

      # The release workflow creates a new branch named exactly as the tag so this must match.
      eas-branch:
        description: What release tag should be published? (It must be the exact name)
        required: true

jobs:
  release:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Select EAS Channel from GitHub Environment
        run: |
          echo ${{ inputs.eas-channel }} | tr '[:upper:]' '[:lower:]' | { var=$(cat); echo "EAS_CHANNEL=${var}"; } >> ${GITHUB_ENV}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: ğŸ— Setup repo
        uses: actions/checkout@v3

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: ğŸ— Enable corepack
        run: |
          corepack enable
          yarn -v

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: ğŸš€ Relink EAS Channel to new EAS Branch
        run: eas channel:edit ${{ env.EAS_CHANNEL }} --non-interactive --branch ${{ inputs.eas-branch }}

